package usaldo

var ns_users = map[string]string{
	// "atma":       "Teguh Atma Wijaya",
	// "adam":       "Nurfalah Adam",
	// "aditya":     "Kevin Aditya Prabowo",
	"nindyatama": "Made Nindyatama Nityasya",
	// "rahmani":    "Nabilla Rahmani Zhafira",
	// "pranyoto":   "Teresa Pranyoto",
	// "izzunaqi":   "Muhammad Izzunnaqi",
	// "azhari":     "Fauzan Azhari",
	"raditya": "Gema Raditya Putra",
	// "radityo":    "Arief Radityo",
	// "putra":      "Bardan Putra Prananto",
	// "saprikan":   "Tommy Saprikan Kahar",
	// "antonius":   "Ferdinand Antonius",
	// "kurniawan":  "Andri Kurniawan",
	// "hadhi":      "Dhanang Hadhi Sasmita",
	// "prayogo":    "Jodi Prayogo",
	// "mardhika":   "Arrianda Mardhika Adif",
	"wicaksono": "Julian Aditya Wicaksono",
	// "anthony":    "Anthony",
	// "kaleb":      "Pusaka Kaleb Setyabudi",
	// "zata":       "Rakina Zata Amni",
	// "wiratmika":  "Wiratmika",
	// "aziz":       "Alief Aziz",
	// "rifai":      "Ahmad Rifai Ashari",
	// "krisitian":  "Kevin Kristian",
	// "alhafis":    "Arsi Alhafis",
	// "rahman":     "Edwin Aditya Rahman",
	"joseph": "Arie Joseph Lonata",
	"saga":   "Adrianus Saga Ekakristi",
	"halim":  "Christian Halim",
	// "prakash":    "Muhammad Prakash Divy Isdarwanto",
	"wijaya": "Alvin Wijaya",
	// "mubarok":    "Rizki Mubarok",
	// "dwiyan":     "Mohamad Dwiyan R",
	// "kurnia":     "Luthfi Kurnia Putra",
	// "rizki":      "Muhammad Rizki Aulia Rahman Maulana",
	"gylberth": "Roan Gylberth",
	// "ratna":      "Desi Ratna Mukti Umpuan",
	// "ilham":      "Ilham Kurniawan",
	// "juan":       "Yeremia Juan Xian Tambunan",
}

var NsKelompok = [8]string{"nindyatama", "raditya", "wicaksono", "joseph", "saga", "halim", "wijaya", "gylberth"}
